# Gathering Data

In [2]:
import pandas as pd
import requests

In [3]:
#loading csv file into jupyter notebook
twitter_df = pd.read_csv('twitter-archive-enhanced.csv')

In [108]:
twitter_df.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

In [5]:


url = 'https://d17h27t6h515a5.cloudfront.net/topher/2017/August/599fd2ad_image-predictions/image-predictions.tsv'

response = requests.get(url)

In [7]:
response.content 
#to see the content

# to saving the data in file named 'image_predictions.tsv' which is same as csv file but elements are separated by tab spaces
with open(url.split('/')[-1], mode='wb') as file:
    file.write(response.content)

In [8]:
#loading data frame into jupyter notebook
image_predictions_df = pd.read_csv('image-predictions.tsv', sep='\t')

In [9]:
image_predictions_df.head()
#image_predictions_df.info()

,tweet_id,jpg_url,img_num,p1,p1_conf,p1_dog,p2,p2_conf,p2_dog,p3,p3_conf,p3_dog
0,666020888022790149,https://pbs.twimg.com/media/CT4udn0WwAA0aMy.jpg,1,Welsh_springer_spaniel,0.465074,True,collie,0.156665,True,Shetland_sheepdog,0.061428,True
1,666029285002620928,https://pbs.twimg.com/media/CT42GRgUYAA5iDo.jpg,1,redbone,0.506826,True,miniature_pinscher,0.074192,True,Rhodesian_ridgeback,0.072010,True
2,666033412701032449,https://pbs.twimg.com/media/CT4521TWwAEvMyu.jpg,1,German_shepherd,0.596461,True,malinois,0.138584,True,bloodhound,0.116197,True
3,666044226329800704,https://pbs.twimg.com/media/CT5Dr8HUEAA-lEu.jpg,1,Rhodesian_ridgeback,0.408143,True,redbone,0.360687,True,miniature_pinscher,0.222752,True
4,666049248165822465,https://pbs.twimg.com/media/CT5IQmsXIAAKY4A.jpg,1,miniature_pinscher,0.560311,True,Rottweiler,0.243682,True,Doberman,0.154629,True

## Query Twitter Data : Using **Tweepy** API

- Tweepy to query Twitter's API for additional data beyond the data included in the WeRateDogs Twitter archive. This additional data will include retweet count and favorite count.

<font color='red'>This Step took around 40-50 minutes in my computer to fetch each user's Data from Twitter</font>

In [93]:
import tweepy
import json
import numpy as np

In [105]:
# all set of tweet_ids

len(list(twitter_df.tweet_id.unique())) # result is 2356 as same as number of tweet ids in twitter_archive_enhanced data frame

2356

In [114]:
list_tweet_ids = list(twitter_df.tweet_id.unique())
list_tweet_ids

[892420643555336193,
 892177421306343426,
 891815181378084864,
 891689557279858688,
 891327558926688256,
 891087950875897856,
 890971913173991426,
 890729181411237888,
 890609185150312448,
 890240255349198849,
 890006608113172480,
 889880896479866881,
 889665388333682689,
 889638837579907072,
 889531135344209921,
 889278841981685760,
 888917238123831296,
 888804989199671297,
 888554962724278272,
 888202515573088257,
 888078434458587136,
 887705289381826560,
 887517139158093824,
 887473957103951883,
 887343217045368832,
 887101392804085760,
 886983233522544640,
 886736880519319552,
 886680336477933568,
 886366144734445568,
 886267009285017600,
 886258384151887873,
 886054160059072513,
 885984800019947520,
 885528943205470208,
 885518971528720385,
 885311592912609280,
 885167619883638784,
 884925521741709313,
 884876753390489601,
 884562892145688576,
 884441805382717440,
 884247878851493888,
 884162670584377345,
 883838122936631299,
 883482846933004288,
 883360690899218434,
 883117836046086144,
 882992080364220416,
 882762694511734784,
 882627270321602560,
 882268110199369728,
 882045870035918850,
 881906580714921986,
 881666595344535552,
 881633300179243008,
 881536004380872706,
 881268444196462592,
 880935762899988482,
 880872448815771648,
 880465832366813184,
 880221127280381952,
 880095782870896641,
 879862464715927552,
 879674319642796034,
 879492040517615616,
 879415818425184262,
 879376492567855104,
 879130579576475649,
 879050749262655488,
 879008229531029506,
 878776093423087618,
 878604707211726852,
 878404777348136964,
 878316110768087041,
 878281511006478336,
 878057613040115712,
 877736472329191424,
 877611172832227328,
 877556246731214848,
 877316821321428993,
 877201837425926144,
 876838120628539392,
 876537666061221889,
 876484053909872640,
 876120275196170240,
 875747767867523072,
 875144289856114688,
 875097192612077568,
 875021211251597312,
 874680097055178752,
 874434818259525634,
 874296783580663808,
 874057562936811520,
 874012996292530176,
 873697596434513921,
 873580283840344065,
 873337748698140672,
 873213775632977920,
 872967104147763200,
 872820683541237760,
 872668790621863937,
 872620804844003328,
 872486979161796608,
 872261713294495745,
 872122724285648897,
 871879754684805121,
 871762521631449091,
 871515927908634625,
 871166179821445120,
 871102520638267392,
 871032628920680449,
 870804317367881728,
 870726314365509632,
 870656317836468226,
 870374049280663552,
 870308999962521604,
 870063196459192321,
 869988702071779329,
 869772420881756160,
 869702957897576449,
 869596645499047938,
 869227993411051520,
 868880397819494401,
 868639477480148993,
 868622495443632128,
 868552278524837888,
 867900495410671616,
 867774946302451713,
 867421006826221569,
 867072653475098625,
 867051520902168576,
 866816280283807744,
 866720684873056260,
 866686824827068416,
 866450705531457537,
 866334964761202691,
 866094527597207552,
 865718153858494464,
 865359393868664832,
 865006731092295680,
 864873206498414592,
 864279568663928832,
 864197398364647424,
 863907417377173506,
 863553081350529029,
 863471782782697472,
 863432100342583297,
 863427515083354112,
 863079547188785154,
 863062471531167744,
 862831371563274240,
 862722525377298433,
 862457590147678208,
 862096992088072192,
 861769973181624320,
 861383897657036800,
 861288531465048066,
 861005113778896900,
 860981674716409858,
 860924035999428608,
 860563773140209665,
 860524505164394496,
 860276583193509888,
 860184849394610176,
 860177593139703809,
 859924526012018688,
 859851578198683649,
 859607811541651456,
 859196978902773760,
 859074603037188101,
 858860390427611136,
 858843525470990336,
 858471635011153920,
 858107933456039936,
 857989990357356544,
 857746408056729600,
 857393404942143489,
 857263160327368704,
 857214891891077121,
 857062103051644929,
 857029823797047296,
 856602993587888130,
 856543823941562368,
 856526610513747968,
 856330835276025856,
 856288084350160898,
 856282028240666624,
 855862651834028034,
 855860136149123072,
 855857698524602368,
 855851453814013952,
 855818117272018944,
 855459453768019968,
 855245323840757760,
 855138241867124737,
 854732716440526848,
 854482394044301312,
 854365224396361728,
 854120357044912130,
 854010172552949760,
 853760880890318849,
 853639147608842240,
 853299958564483072,
 852936405516943360,
 852912242202992640,
 852672615818899456,
 852553447878664193,
 852311364735569921,
 852226086759018497,
 852189679701164033,
 851953902622658560,
 851861385021730816,
 851591660324737024,
 851464819735769094,
 851224888060895234,
 850753642995093505,
 850380195714523136,
 850333567704068097,
 850145622816686080,
 850019790995546112,
 849776966551130114,
 849668094696017920,
 849412302885593088,
 849336543269576704,
 849051919805034497,
 848690551926992896,
 848324959059550208,
 848213670039564288,
 848212111729840128,
 847978865427394560,
 847971574464610304,
 847962785489326080,
 847842811428974592,
 847617282490613760,
 847606175596138505,
 847251039262605312,
 847157206088847362,
 847116187444137987,
 846874817362120707,
 846514051647705089,
 846505985330044928,
 846153765933735936,
 846139713627017216,
 846042936437604353,
 845812042753855489,
 845677943972139009,
 845459076796616705,
 845397057150107648,
 845306882940190720,
 845098359547420673,
 844979544864018432,
 844973813909606400,
 844704788403113984,
 844580511645339650,
 844223788422217728,
 843981021012017153,
 843856843873095681,
 843604394117681152,
 843235543001513987,
 842892208864923648,
 842846295480000512,
 842765311967449089,
 842535590457499648,
 842163532590374912,
 842115215311396866,
 841833993020538882,
 841680585030541313,
 841439858740625411,
 841320156043304961,
 841314665196081154,
 841077006473256960,
 840761248237133825,
 840728873075638272,
 840698636975636481,
 840696689258311684,
 840632337062862849,
 840370681858686976,
 840268004936019968,
 839990271299457024,
 839549326359670784,
 839290600511926273,
 839239871831150596,
 838952994649550848,
 838921590096166913,
 838916489579200512,
 838831947270979586,
 838561493054533637,
 838476387338051585,
 838201503651401729,
 838150277551247360,
 838085839343206401,
 838083903487373313,
 837820167694528512,
 837482249356513284,
 837471256429613056,
 837366284874571778,
 837110210464448512,
 837012587749474308,
 836989968035819520,
 836753516572119041,
 836677758902222849,
 836648853927522308,
 836397794269200385,
 836380477523124226,
 836260088725786625,
 836001077879255040,
 835685285446955009,
 835574547218894849,
 835536468978302976,
 835309094223372289,
 835297930240217089,
 835264098648616962,
 835246439529840640,
 835172783151792128,
 835152434251116546,
 834931633769889797,
 834786237630337024,
 834574053763584002,
 834477809192075265,
 834458053273591808,
 834209720923721728,
 834167344700198914,
 834089966724603904,
 834086379323871233,
 833863086058651648,
 833826103416520705,
 833732339549220864,
 833722901757046785,
 833479644947025920,
 833124694597443584,
 832998151111966721,
 832769181346996225,
 832757312314028032,
 832682457690300417,
 832645525019123713,
 832636094638288896,
 832397543355072512,
 832369877331693569,
 832273440279240704,
 832215909146226688,
 832215726631055365,
 832088576586297345,
 832040443403784192,
 832032802820481025,
 831939777352105988,
 831926988323639298,
 831911600680497154,
 831670449226514432,
 831650051525054464,
 831552930092285952,
 831322785565769729,
 831315979191906304,
 831309418084069378,
 831262627380748289,
 830956169170665475,
 830583320585068544,
 830173239259324417,
 830097400375152640,
 829878982036299777,
 829861396166877184,
 829501995190984704,
 829449946868879360,
 829374341691346946,
 829141528400556032,
 829011960981237760,
 828801551087042563,
 828770345708580865,
 828708714936930305,
 828650029636317184,
 828409743546925057,
 828408677031882754,
 828381636999917570,
 828376505180889089,
 828372645993398273,
 828361771580813312,
 828046555563323392,
 828011680017821696,
 827933404142436356,
 827653905312006145,
 827600520311402496,
 827324948884643840,
 827228250799742977,
 827199976799354881,
 826958653328592898,
 826848821049180160,
 826615380357632002,
 826598799820865537,
 826598365270007810,
 826476773533745153,
 826240494070030336,
 826204788643753985,
 826115272272650244,
 825876512159186944,
 825829644528148480,
 825535076884762624,
 825147591692263424,
 825120256414846976,
 825026590719483904,
 824796380199809024,
 824775126675836928,
 824663926340194305,
 824325613288833024,
 824297048279236611,
 824025158776213504,
 823939628516474880,
 823719002937630720,
 823699002998870016,
 823581115634085888,
 823333489516937216,
 823322678127919110,
 823269594223824897,
 822975315408461824,
 822872901745569793,
 822859134160621569,
 822647212903690241,
 822610361945911296,
 822489057087389700,
 822462944365645825,
 822244816520155136,
 822163064745328640,
 821886076407029760,
 821813639212650496,
 821765923262631936,
 821522889702862852,
 821421320206483457,
 821407182352777218,
 821153421864615936,
 821149554670182400,
 821107785811234820,
 821044531881721856,
 820837357901512704,
 820749716845686786,
 820690176645140481,
 820494788566847489,
 820446719150292993,
 820314633777061888,
 820078625395449857,
 820013781606658049,
 819952236453363712,
 819924195358416896,
 819711362133872643,
 819588359383371776,
 819347104292290561,
 819238181065359361,
 819227688460238848,
 819015337530290176,
 819015331746349057,
 819006400881917954,
 819004803107983360,
 818646164899774465,
 818627210458333184,
 818614493328580609,
 818588835076603904,
 818536468981415936,
 818307523543449600,
 818259473185828864,
 818145370475810820,
 817908911860748288,
 817827839487737858,
 817777686764523521,
 817536400337801217,
 817502432452313088,
 817423860136083457,
 817415592588222464,
 817181837579653120,
 817171292965273600,
 817120970343411712,
 817056546584727552,
 816829038950027264,
 816816676327063552,
 816697700272001025,
 816450570814898180,
 816336735214911488,
 816091915477250048,
 816062466425819140,
 816014286006976512,
 815990720817401858,
 815966073409433600,
 815745968457060357,
 815736392542261248,
 815639385530101762,
 815390420867969024,
 814986499976527872,
 814638523311648768,
 814578408554463233,
 814530161257443328,
 814153002265309185,
 813944609378369540,
 813910438903693312,
 813812741911748608,
 813800681631023104,
 813217897535406080,
 813202720496779264,
 813187593374461952,
 813172488309972993,
 813157409116065792,
 813142292504645637,
 813130366689148928,
 813127251579564032,
 813112105746448384,
 813096984823349248,
 813081950185472002,
 813066809284972545,
 813051746834595840,
 812781120811126785,
 812747805718642688,
 812709060537683968,
 812503143955202048,
 812466873996607488,
 812372279581671427,
 811985624773361665,
 811744202451197953,
 811647686436880384,
 811627233043480576,
 811386762094317568,
 810984652412424192,
 810896069567610880,
 810657578271330305,
 810284430598270976,
 810254108431155201,
 809920764300447744,
 809808892968534016,
 809448704142938112,
 809220051211603969,
 809084759137812480,
 808838249661788160,
 808733504066486276,
 808501579447930884,
 808344865868283904,
 808134635716833280,
 808106460588765185,
 808001312164028416,
 807621403335917568,
 807106840509214720,
 807059379405148160,
 807010152071229440,
 806629075125202948,
 806620845233815552,
 806576416489959424,
 806542213899489280,
 806242860592926720,
 806219024703037440,
 805958939288408065,
 805932879469572096,
 805826884734976000,
 805823200554876929,
 805520635690676224,
 805487436403003392,
 805207613751304193,
 804738756058218496,
 804475857670639616,
 804413760345620481,
 804026241225523202,
 803773340896923648,
 803692223237865472,
 803638050916102144,
 803380650405482500,
 803321560782307329,
 803276597545603072,
 802952499103731712,
 802624713319034886,
 802600418706604034,
 802572683846291456,
 802323869084381190,
 802265048156610565,
 802247111496568832,
 802239329049477120,
 802185808107208704,
 801958328846974976,
 801854953262350336,
 801538201127157760,
 801285448605831168,
 801167903437357056,
 801127390143516673,
 801115127852503040,
 800859414831898624,
 800855607700029440,
 800751577355128832,
 800513324630806528,
 800459316964663297,
 800443802682937345,
 800388270626521089,
 800188575492947969,
 800141422401830912,
 800018252395122689,
 799774291445383169,
 799757965289017345,
 799422933579902976,
 799308762079035393,
 799297110730567681,
 799063482566066176,
 798933969379225600,
 798925684722855936,
 798705661114773508,
 798701998996647937,
 798697898615730177,
 798694562394996736,
 798686750113755136,
 798682547630837760,
 798673117451325440,
 798665375516884993,
 798644042770751489,
 798628517273620480,
 798585098161549313,
 798576900688019456,
 798340744599797760,
 798209839306514432,
 797971864723324932,
 797545162159308800,
 797236660651966464,
 797165961484890113,
 796904159865868288,
 796865951799083009,
 796759840936919040,
 796563435802726400,
 796484825502875648,
 796387464403357696,
 796177847564038144,
 796149749086875649,
 796125600683540480,
 796116448414461957,
 796080075804475393,
 796031486298386433,
 795464331001561088,
 795400264262053889,
 795076730285391872,
 794983741416415232,
 794926597468000259,
 794355576146903043,
 794332329137291264,
 794205286408003585,
 793962221541933056,
 793845145112371200,
 793614319594401792,
 793601777308463104,
 793500921481273345,
 793286476301799424,
 793271401113350145,
 793256262322548741,
 793241302385262592,
 793226087023144960,
 793210959003287553,
 793195938047070209,
 793180763617361921,
 793165685325201412,
 793150605191548928,
 793135492858580992,
 793120401413079041,
 792913359805018113,
 792883833364439040,
 792773781206999040,
 792394556390137856,
 792050063153438720,
 791821351946420224,
 791784077045166082,
 791780927877898241,
 791774931465953280,
 791672322847637504,
 791406955684368384,
 791312159183634433,
 791026214425268224,
 790987426131050500,
 790946055508652032,
 790723298204217344,
 790698755171364864,
 790581949425475584,
 790337589677002753,
 790277117346975746,
 790227638568808452,
 789986466051088384,
 789960241177853952,
 789903600034189313,
 789628658055020548,
 789599242079838210,
 789530877013393408,
 789314372632018944,
 789280767834746880,
 789268448748703744,
 789137962068021249,
 788908386943430656,
 788765914992902144,
 788552643979468800,
 788412144018661376,
 788178268662984705,
 788150585577050112,
 788070120937619456,
 788039637453406209,
 787810552592695296,
 787717603741622272,
 787397959788929025,
 787322443945877504,
 787111942498508800,
 786963064373534720,
 786729988674449408,
 786709082849828864,
 786664955043049472,
 786595970293370880,
 786363235746385920,
 786286427768250368,
 786233965241827333,
 786051337297522688,
 786036967502913536,
 785927819176054784,
 785872687017132033,
 785639753186217984,
 785533386513321988,
 785515384317313025,
 785264754247995392,
 785170936622350336,
 784826020293709826,
 784517518371221505,
 784431430411685888,
 784183165795655680,
 784057939640352768,
 783839966405230592,
 783821107061198850,
 783695101801398276,
 783466772167098368,
 783391753726550016,
 783347506784731136,
 783334639985389568,
 783085703974514689,
 782969140009107456,
 782747134529531904,
 782722598790725632,
 782598640137187329,
 782305867769217024,
 782021823840026624,
 781955203444699136,
 781661882474196992,
 781655249211752448,
 781524693396357120,
 781308096455073793,
 781251288990355457,
 781163403222056960,
 780931614150983680,
 780858289093574656,
 780800785462489090,
 780601303617732608,
 780543529827336192,
 780496263422808064,
 780476555013349377,
 780459368902959104,
 780192070812196864,
 780092040432480260,
 780074436359819264,
 779834332596887552,
 779377524342161408,
 779124354206535695,
 779123168116150273,
 779056095788752897,
 778990705243029504,
 778774459159379968,
 778764940568104960,
 778748913645780993,
 778650543019483137,
 778624900596654080,
 778408200802557953,
 778396591732486144,
 778383385161035776,
 778286810187399168,
 778039087836069888,
 778027034220126208,
 777953400541634568,
 777885040357281792,
 777684233540206592,
 777641927919427584,
 777621514455814149,
 777189768882946048,
 776819012571455488,
 776813020089548800,
 776477788987613185,
 776249906839351296,
 776218204058357768,
 776201521193218049,
 776113305656188928,
 776088319444877312,
 775898661951791106,
 775842724423557120,
 775733305207554048,
 775729183532220416,
 775364825476165632,
 775350846108426240,
 775096608509886464,
 775085132600442880,
 774757898236878852,
 774639387460112384,
 774314403806253056,
 773985732834758656,
 773922284943896577,
 773704687002451968,
 773670353721753600,
 773547596996571136,
 773336787167145985,
 773308824254029826,
 773247561583001600,
 773191612633579521,
 772877495989305348,
 772826264096874500,
 772615324260794368,
 772581559778025472,
 772193107915964416,
 772152991789019136,
 772117678702071809,
 772114945936949249,
 772102971039580160,
 771908950375665664,
 771770456517009408,
 771500966810099713,
 771380798096281600,
 771171053431250945,
 771136648247640064,
 771102124360998913,
 771014301343748096,
 771004394259247104,
 770787852854652928,
 770772759874076672,
 770743923962707968,
 770655142660169732,
 770414278348247044,
 770293558247038976,
 770093767776997377,
 770069151037685760,
 769940425801170949,
 769695466921623552,
 769335591808995329,
 769212283578875904,
 768970937022709760,
 768909767477751808,
 768855141948723200,
 768609597686943744,
 768596291618299904,
 768554158521745409,
 768473857036525572,
 768193404517830656,
 767884188863397888,
 767754930266464257,
 767500508068192258,
 767191397493538821,
 767122157629476866,
 766864461642756096,
 766793450729734144,
 766714921925144576,
 766693177336135680,
 766423258543644672,
 766313316352462849,
 766078092750233600,
 766069199026450432,
 766008592277377025,
 765719909049503744,
 765669560888528897,
 765395769549590528,
 765371061932261376,
 765222098633691136,
 764857477905154048,
 764259802650378240,
 763956972077010945,
 763837565564780549,
 763183847194451968,
 763167063695355904,
 763103485927849985,
 762699858130116608,
 762471784394268675,
 762464539388485633,
 762316489655476224,
 762035686371364864,
 761976711479193600,
 761750502866649088,
 761745352076779520,
 761672994376806400,
 761599872357261312,
 761371037149827077,
 761334018830917632,
 761292947749015552,
 761227390836215808,
 761004547850530816,
 760893934457552897,
 760656994973933572,
 760641137271070720,
 760539183865880579,
 760521673607086080,
 760290219849637889,
 760252756032651264,
 760190180481531904,
 760153949710192640,
 759943073749200896,
 759923798737051648,
 759846353224826880,
 759793422261743616,
 759566828574212096,
 759557299618865152,
 759447681597108224,
 759446261539934208,
 759197388317847553,
 759159934323924993,
 759099523532779520,
 759047813560868866,
 758854675097526272,
 758828659922702336,
 758740312047005698,
 758474966123810816,
 758467244762497024,
 758405701903519748,
 758355060040593408,
 758099635764359168,
 758041019896193024,
 757741869644341248,
 757729163776290825,
 757725642876129280,
 757611664640446465,
 757597904299253760,
 757596066325864448,
 757400162377592832,
 757393109802180609,
 757354760399941633,
 756998049151549440,
 756939218950160384,
 756651752796094464,
 756526248105566208,
 756303284449767430,
 756288534030475264,
 756275833623502848,
 755955933503782912,
 755206590534418437,
 755110668769038337,
 754874841593970688,
 754856583969079297,
 754747087846248448,
 754482103782404096,
 754449512966619136,
 754120377874386944,
 754011816964026368,
 753655901052166144,
 753420520834629632,
 753398408988139520,
 753375668877008896,
 753298634498793472,
 753294487569522689,
 753039830821511168,
 753026973505581056,
 752932432744185856,
 752917284578922496,
 752701944171524096,
 752682090207055872,
 752660715232722944,
 752568224206688256,
 752519690950500352,
 752334515931054080,
 752309394570878976,
 752173152931807232,
 751950017322246144,

In [22]:
# authentication of API
consumer_key = 'gTnWhHWZGYZ3p4ALDX32ady9h'
consumer_secret = 'YspcOuc5fNWJDDVZXkXyxkhEi39xx6lHPOUHifeqJUNQjS4c5g'
access_token = '901902198602391552-HKHv1LxR4ESXCosZ5dVXmCX0cavnmB2'
access_secret = 'b9rcIiTgAh9S5Zv7PVeWrelgkfxLwU8KuN2E7Ulx8Rwex'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth,wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

In [257]:
# fetching each tweet ids data from API and storing it into file
# named 'tweet_json.txt' we only store 
#  1.tweet_id
#  2.retweet_count
#  3.favorite_count

data = {}
data['people']=[]
counter=0
for tweet_id in list_tweet_ids:
    try:
        counter=counter+1
        print(counter)
        tweet = api.get_status(tweet_id,tweet_mode='extended')
        tweet_id = tweet_id
        retweet_count = tweet._json['retweet_count']
        favorite_count = tweet._json['favorite_count']
        data['people'].append({
            'tweet_id':tweet_id,
            'retweet_count':retweet_count,
            'favorite_count':favorite_count
        })
    except Exception as e:
        print(str(e))

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
[{'code': 144, 'message': 'No status found with that ID.'}]
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
[{'code': 144, 'message': 'No status found with that ID.'}]
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
[{'code': 144, 'message': 'No status found with that ID.'}]
120
121
122
123
124
125
126
127
128
129
130
131
132
133
[{'code': 144, 'message': 'No status found with that ID.'}]
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
[{'code': 144, 'message': 'No status found with that ID.'}]
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
[{'code': 144, 'message': 'No status found with that ID.'}]
249
250
251
252
253
254
255
256
257
258
259
260
261
[{'code': 144, 'message': 'No status found with that ID.'}]
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
[{'code': 144, 'message': 'No status found with that ID.'}]
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
[{'code': 144, 'message': 'No status found with that ID.'}]
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
[{'code': 144, 'message': 'No status found with that ID.'}]
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
[{'code': 144, 'message': 'No status found with that ID.'}]
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
864
865
866
867
868
869
870
871
872
873
874
875
876
877
878
879
880
881
882
883
884
885
886
887
888
889
890
891
892
893
894
895
896
897
898
899
900
901
902
903
904
905
906
907
908
909
910
911
912
913
914
915
916
917
918
919
920
921
922
923
924
925
926
927
928
929
930
931
932
933
[{'code': 144, 'message': 'No status found with that ID.'}]
934
935
936
937
938
939
940
941
942
943
944
945
946
947
948
949
950
951
952
953
954
955
956
957
958
959
960
961
962
963
964
965
966
967
968
969
970
971
972
973
974
975
976
977
978
979
980
981
982
983
984
985
986
987
988
989
990
991
992
993
994
995
996
997
998
999
1000
1001
1002
1003
1004
1005
1006
1007
1008
1009
1010
1011
1012
1013
1014
1015
1016
1017
1018
1019
1020
1021
1022
1023
1024
1025
1026
1027
1028
1029
1030
1031
1032
1033
1034
1035
1036
1037
1038
1039
1040
1041
1042
1043
1044
1045
1046
1047
1048
1049
1050
1051
1052
1053
1054
1055
1056
1057
1058
1059
1060
1061
1062
1063
1064
1065
1066
1067
1068
1069
1070
1071
1072
1073
1074
1075
1076
1077
1078
1079
1080
1081
1082
1083
1084
1085
1086
1087
1088
1089
1090
1091
1092
1093
1094
1095
1096
1097
1098
1099
1100
1101
1102
1103
1104
1105
1106
1107
1108
1109
1110
1111
1112
1113
1114
1115
1116
1117
1118
1119
1120
1121
1122
1123
1124
1125
1126
1127
1128
1129
1130
1131
1132
1133
1134
1135
1136
1137
1138
1139
1140
1141
1142
1143
1144
1145
1146
1147
1148
1149
1150
1151
1152
1153
1154
1155
1156
1157
1158
1159
1160
1161
1162
1163
1164
1165
1166
1167
1168
1169
1170
1171
1172
1173
1174
1175
1176
1177
1178
1179
1180
1181
1182
1183
1184
1185
1186
1187
1188
1189
1190
1191
1192
1193
1194
1195
1196
1197
1198
1199
1200
1201
1202
1203
1204
1205
1206
1207
1208
1209
1210
1211
1212
1213
1214
1215
1216
1217
1218
1219
1220
1221
1222
1223
1224
1225
1226
1227
1228
1229
1230
1231
1232
1233
1234
1235
1236
1237
1238
1239
1240
1241
1242
1243
1244
1245
1246
1247
1248
1249
1250
1251
1252
1253
1254
1255
1256
1257
1258
1259
1260
1261
1262
1263
1264
1265
1266
1267
1268
1269
1270
1271
1272
1273
1274
1275
1276
1277
1278
1279
1280
1281
1282
1283
1284
1285
1286
1287
1288
1289
1290
1291
1292
1293
1294
1295
1296
1297
1298
1299
1300
1301
1302
1303
1304
1305
1306
1307
1308
1309
1310
1311
1312
1313
1314
1315
1316
1317
1318
1319
1320
1321
1322
1323
1324
1325
1326
1327
1328
1329
1330
1331
1332
1333
1334
1335
1336
1337
1338
1339
1340
1341
1342
1343
1344
1345
1346
1347
1348
1349
1350
1351
1352
1353
1354
1355
1356
1357
1358
1359
1360
1361
1362
1363
1364
1365
1366
1367
1368
1369
1370
1371
1372
1373
1374
1375
1376
1377
1378
1379
1380
1381
1382
1383
1384
1385
1386
1387
1388
1389
1390
1391
1392
1393
1394
1395
1396
1397
1398
1399
1400
1401
1402
1403
1404
1405
1406
1407
1408
1409
1410
1411
1412
1413
1414
1415
1416
1417
1418
1419
1420
1421
1422
1423
1424
1425
1426
1427
1428
1429
1430
1431
1432
1433
1434
1435
1436
1437
1438
1439
1440
1441
1442
1443
1444
1445
1446
1447
1448
1449
1450
1451
1452
1453
1454
1455
1456
1457
1458
1459
1460
1461
1462
1463
1464
1465
1466
1467
1468
1469
1470
1471
1472
1473
1474
1475
1476
1477
1478
1479
1480
1481
1482
1483
1484
1485
1486
1487
1488
1489
1490
1491
1492
1493
1494
1495
1496
1497
1498
1499
1500
1501
1502
1503
1504
1505
1506
1507
1508
1509
1510
1511
1512
1513
1514
1515
1516
1517
1518
1519
1520
1521
1522
1523
1524
1525
1526
1527
1528
1529
1530
1531
1532
1533
1534
1535
1536
1537
1538
1539
1540
1541
1542
1543
1544
1545
1546
1547
1548
1549
1550
1551
1552
1553
1554
1555
1556
1557
1558
1559
1560
1561
1562
1563
1564
1565
1566
1567
1568
1569
1570
1571
1572
1573
1574
1575
1576
1577
1578
1579
1580
1581
1582
1583
1584
1585
1586
1587
1588
1589
1590
1591
1592
1593
1594
1595
1596
1597
1598
1599
1600
1601
1602
1603
1604
1605
1606
1607
1608
1609
1610
1611
1612
1613
1614
1615
1616
1617
1618
1619
1620
1621
1622
1623
1624
1625
1626
1627
1628
1629
1630
1631
1632
1633
1634
1635
1636
1637
1638
1639
1640
1641
1642
1643
1644
1645
1646
1647
1648
1649
1650
1651
1652
1653
1654
1655
1656
1657
1658
1659
1660
1661
1662
1663
1664
1665
1666
1667
1668
1669
1670
1671
1672
1673
1674
1675
1676
1677
1678
1679
1680
1681
1682
1683
1684
1685
1686
1687
1688
1689
1690
1691
1692
1693
1694
1695
1696
1697
1698
1699
1700
1701
1702
1703
1704
1705
1706
1707
1708
1709
1710
1711
1712
1713
1714
1715
1716

1717
1718
1719
1720
1721
1722
1723
1724
1725
1726
1727
1728
1729
1730
1731
1732
1733
1734
1735
1736
1737
1738
1739
1740
1741
1742
1743
1744
1745
1746
1747
1748
1749
1750
1751
1752
1753
1754
1755
1756
1757
1758
1759
1760
1761
1762
1763
1764
1765
1766
1767
1768
1769
1770
1771
1772
1773
1774
1775
1776
1777
1778
1779
1780
1781
1782
1783
1784
1785
1786
1787
1788
1789
1790
1791
1792
1793
1794
1795
1796
1797
1798
1799
1800
1801
1802
1803
1804
1805
1806
1807
1808
1809
1810
1811
1812
1813
1814
1815
1816
1817
1818
1819
1820
1821
1822
1823
1824
1825
1826
1827
1828
1829
1830
1831
1832
1833
1834
1835
1836
1837
1838
1839
1840
1841
1842
1843
1844
1845
1846
1847
1848
1849
1850
1851
1852
1853
1854
1855
1856
1857
1858
1859
1860
1861
1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236
2237
2238
2239
2240
2241
2242
2243
2244
2245
2246
2247
2248
2249
2250
2251
2252
2253
2254
2255
2256
2257
2258
2259
2260
2261
2262
2263
2264
2265
2266
2267
2268
2269
2270
2271
2272
2273
2274
2275
2276
2277
2278
2279
2280
2281
2282
2283
2284
2285
2286
2287
2288
2289
2290
2291
2292
2293
2294
2295
2296
2297
2298
2299
2300
2301
2302
2303
2304
2305
2306
2307
2308
2309
2310
2311
2312
2313
2314
2315
2316
2317
2318
2319
2320
2321
2322
2323
2324
2325
2326
2327
2328
2329
2330
2331
2332
2333
2334
2335
2336
2337
2338
2339
2340
2341
2342
2343
2344
2345
2346
2347
2348
2349
2350
2351
2352
2353
2354
2355
2356

In [255]:
# checking retweet count and favorite count
t = api.get_status(891689557279858688,tweet_mode='extended')

In [256]:
print(t._json['retweet_count'])
print(t._json['favorite_count'])

8678
42033

In [258]:
for item in data['people']:
    item['tweet_id']=str(item['tweet_id'])
    item['retweet_count']=str(item['retweet_count'])
    item['favorite_count']=str(item['favorite_count'])

In [259]:
type(data)

dict

In [261]:
# now dumps the json created to file named 'tweet_json.txt'
with open('tweet_json.txt', 'w') as outfile:  
    json.dump(data, outfile)

In [262]:
#Reading and appending to the list variable, whixh holds dictionary
dict_list=[]
with open('tweet_json.txt') as json_file:
    data = json.load(json_file)
    for p in data['people']:
        dict_list.append({
                'tweet_id':int(p['tweet_id']),
                'retweet_count':int(p['retweet_count']),
                'favorite_count':int(p['favorite_count'])
            })

In [263]:
# read this file, line by line, to create a pandas DataFrame
API_df = pd.DataFrame(dict_list, columns = ['tweet_id', 'retweet_count', 'favorite_count'])
API_df.head()

             tweet_id  retweet_count  favorite_count
0  892420643555336193           8549           38662
1  892177421306343426           6286           33126
2  891815181378084864           4166           24940
3  891689557279858688           8678           42033
4  891327558926688256           9435           40190

## <font color='red'> Storing Gathered Data to DataBase</font>

### Connect to database

In [153]:
from sqlalchemy import create_engine

In [154]:
engine = create_engine('sqlite:///twitter.db')

### Storing data from dataframe in database

In [264]:
twitter_df.to_sql('table1',engine,index=False)
image_predictions_df.to_sql('table2',engine,index=False)
API_df.to_sql('table3',engine,index=False)

### Importing data from database to dataframe

In [265]:
# just for checking 
df = pd.read_sql('SELECT * FROM table4',engine)
df.head()==API_df.head() # result is true for all values

   tweet_id  retweet_count  favorite_count
0      True           True            True
1      True           True            True
2      True           True            True
3      True           True            True
4      True           True            True

# Assessing Data for this Project

## <font color='Blue'>QUALITY:</font>
### twitter_df table
- wrong datatype for timestamp column and retweeted_status_timestamp
- rating_denominator is not 10 for some observations that should be taken as 10 and same ration the numerator be reduced
- for row 47 and 765 wrong extraction is taken place 11.27 to 27 qnd 13.5 to 5 means wrong conversion is taken for decimal point numerator.
- since we have only 4 types of sources so it must be categorised.
- wrongly extraction of name {'a','an'} in name column, there must be none in place.
- missing expanded_urls filling with it using given tweet_id
- mixing of time and date in timestamp
- wrong data type of retweeted and favorite count(also slice the .0 part)
## image_prediction_df
- Change the names of columns to descriptive one. i.e., __p1 to algo_predict1__ , __p1_conf to algo_predict1_conf__ and so on.


## <font color='Blue'>TIDINESS:</font>
- **timestamp** column in twitter_df should be split into **date** and **time** column
- Four variables dog "stage" (i.e. doggo, floofer, pupper, and puppo)  in 1 column knows as 'stages'
- **API_df** should be part of **twitter_df**

In [170]:
twitter_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2297 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

In [345]:
twitter_df.timestamp.head()

0    2017-08-01 16:23:56 +0000
1    2017-08-01 00:17:27 +0000
2    2017-07-31 00:18:03 +0000
3    2017-07-30 15:58:51 +0000
4    2017-07-29 16:00:24 +0000
Name: timestamp, dtype: object

In [356]:
# finding not null expanded URLs
d2=twitter_df[twitter_df.expanded_urls.notnull()].copy()
d2.expanded_urls.str.split("/",-1,expand=True)

,0,1,2,3,4,5,6,7,8,9,...,47,48,49,50,51,52,53,54,55,56
0,https:,,twitter.com,dog_rates,status,892420643555336193,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
1,https:,,twitter.com,dog_rates,status,892177421306343426,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2,https:,,twitter.com,dog_rates,status,891815181378084864,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
3,https:,,twitter.com,dog_rates,status,891689557279858688,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
4,https:,,twitter.com,dog_rates,status,891327558926688256,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
5,https:,,twitter.com,dog_rates,status,891087950875897856,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
6,https:,,gofundme.com,"ydvmve-surgery-for-jax,https:",,twitter.com,dog_rates,status,890971913173991426,photo,...,None,None,None,None,None,None,None,None,None,None
7,https:,,twitter.com,dog_rates,status,890729181411237888,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
8,https:,,twitter.com,dog_rates,status,890609185150312448,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
9,https:,,twitter.com,dog_rates,status,890240255349198849,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
10,https:,,twitter.com,dog_rates,status,890006608113172480,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
11,https:,,twitter.com,dog_rates,status,889880896479866881,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
12,https:,,twitter.com,dog_rates,status,889665388333682689,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
13,https:,,twitter.com,dog_rates,status,889638837579907072,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
14,https:,,twitter.com,dog_rates,status,889531135344209921,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
15,https:,,twitter.com,dog_rates,status,889278841981685760,video,1,None,None,...,None,None,None,None,None,None,None,None,None,None
16,https:,,twitter.com,dog_rates,status,888917238123831296,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
17,https:,,twitter.com,dog_rates,status,888804989199671297,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
18,https:,,twitter.com,dog_rates,status,888554962724278272,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
19,https:,,twitter.com,dog_rates,status,887473957103951883,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
20,https:,,twitter.com,dog_rates,status,888078434458587136,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
21,https:,,twitter.com,dog_rates,status,887705289381826560,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
22,https:,,twitter.com,dog_rates,status,887517139158093824,video,1,None,None,...,None,None,None,None,None,None,None,None,None,None
23,https:,,twitter.com,dog_rates,status,887473957103951883,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
24,https:,,twitter.com,dog_rates,status,887343217045368832,video,1,None,None,...,None,None,None,None,None,None,None,None,None,None
25,https:,,twitter.com,dog_rates,status,887101392804085760,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
26,https:,,twitter.com,dog_rates,status,886983233522544640,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
27,https:,,www.gofundme.com,"mingusneedsus,https:",,twitter.com,dog_rates,status,886736880519319552,photo,...,None,None,None,None,None,None,None,None,None,None
28,https:,,twitter.com,dog_rates,status,886680336477933568,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
29,https:,,twitter.com,dog_rates,status,886366144734445568,photo,"1,https:",,twitter.com,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326,https:,,twitter.com,dog_rates,status,666411507551481857,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2327,https:,,twitter.com,dog_rates,status,666407126856765440,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2328,https:,,twitter.com,dog_rates,status,666396247373291520,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2329,https:,,twitter.com,dog_rates,status,666373753744588802,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2330,https:,,twitter.com,dog_rates,status,666362758909284353,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2331,https:,,twitter.com,dog_rates,status,666353288456101888,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2332,https:,,twitter.com,dog_rates,status,666345417576210432,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2333,https:,,twitter.com,dog_rates,status,666337882303524864,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2334,https:,,twitter.com,dog_rates,status,666293911632134144,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2335,https:,,twitter.com,dog_rates,status,666287406224695296,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2336,https:,,twitter.com,dog_rates,status,666273097616637952,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2337,https:,,twitter.com,dog_rates,status,666268910803644416,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2338,https:,,twitter.com,dog_rates,status,666104133288665088,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2339,https:,,twitter.com,dog_rates,status,666102155909144576,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2340,https:,,twitter.com,dog_rates,status,666099513787052032,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2341,https:,,twitter.com,dog_rates,status,666094000022159362,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2342,https:,,twitter.com,dog_rates,status,666082916733198337,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2343,https:,,twitter.com,dog_rates,status,666073100786774016,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2344,https:,,twitter.com,dog_rates,status,666071193221509120,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2345,https:,,twitter.com,dog_rates,status,666063827256086533,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2346,https:,,twitter.com,dog_rates,status,666058600524156928,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2347,https:,,twitter.com,dog_rates,status,666057090499244032,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2348,https:,,twitter.com,dog_rates,status,666055525042405380,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2349,https:,,twitter.com,dog_rates,status,666051853826850816,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2350,https:,,twitter.com,dog_rates,status,666050758794694657,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2351,https:,,twitter.com,dog_rates,status,666049248165822465,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2352,https:,,twitter.com,dog_rates,status,666044226329800704,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2353,https:,,twitter.com,dog_rates,status,666033412701032449,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2354,https:,,twitter.com,dog_rates,status,666029285002620928,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None
2355,https:,,twitter.com,dog_rates,status,666020888022790149,photo,1,None,None,...,None,None,None,None,None,None,None,None,None,None

In [236]:
twitter_df[twitter_df['name']=='a']
twitter_df[twitter_df['name']=='an']

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
759,778396591732486144,NaN,NaN,2016-09-21 00:53:04 +0000,"<a href=""http://twitter.com/download/iphone"" r...",RT @dog_rates: This is an East African Chalupa...,7.030419e+17,4.196984e+09,2016-02-26 02:20:37 +0000,https://twitter.com/dog_rates/status/703041949...,10,10,an,None,None,None,None
1025,746369468511756288,NaN,NaN,2016-06-24 15:48:42 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an Iraqi Speed Kangaroo. It is not a d...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/746369468...,9,10,an,None,None,None,None
1362,703041949650034688,NaN,NaN,2016-02-26 02:20:37 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an East African Chalupa Seal. We only ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/703041949...,10,10,an,None,None,None,None
2204,668636665813057536,NaN,NaN,2015-11-23 03:46:18 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an Irish Rigatoni terrier named Berta....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/668636665...,10,10,an,None,None,None,None
2333,666337882303524864,NaN,NaN,2015-11-16 19:31:45 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an extremely rare horned Parthenon. No...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666337882...,9,10,an,None,None,None,None
2335,666287406224695296,NaN,NaN,2015-11-16 16:11:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an Albanian 3 1/2 legged Episcopalian...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666287406...,1,2,an,None,None,None,None
2349,666051853826850816,NaN,NaN,2015-11-16 00:35:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an odd dog. Hard on the outside but lo...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666051853...,2,10,an,None,None,None,None

In [229]:
twitter_df.name.value_counts()

None        745
a            55
Charlie      12
Lucy         11
Oliver       11
Cooper       11
Tucker       10
Penny        10
Lola         10
Bo            9
Winston       9
Sadie         8
the           8
Bailey        7
Toby          7
Daisy         7
an            7
Buddy         7
Koda          6
Milo          6
Jack          6
Rusty         6
Stanley       6
Leo           6
Bella         6
Scout         6
Dave          6
Jax           6
Oscar         6
Gus           5
           ...
Leonidas      1
Lillie        1
Kramer        1
Mollie        1
Danny         1
Monster       1
Zooey         1
Dale          1
Dewey         1
Kevon         1
Anna          1
Grizz         1
Jerome        1
Cora          1
Izzy          1
Lupe          1
Maisey        1
Caryl         1
Burt          1
Spanky        1
Fiji          1
Kial          1
Link          1
Murphy        1
Ace           1
Obi           1
Philippe      1
Zuzu          1
Brutus        1
Goliath       1
Name: name, Length: 957, dtype: int64

In [235]:
twitter_df.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
0,892420643555336193,NaN,NaN,2017-08-01 16:23:56 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None
1,892177421306343426,NaN,NaN,2017-08-01 00:17:27 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaN,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None
2,891815181378084864,NaN,NaN,2017-07-31 00:18:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None
3,891689557279858688,NaN,NaN,2017-07-30 15:58:51 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None
4,891327558926688256,NaN,NaN,2017-07-29 16:00:24 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None

In [245]:
#data for which rating_denominator  is not 10, Actually it is calculated other than 10 wrongly
twitter_df.query('rating_denominator != 10')

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,timestamp,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo
313,835246439529840640,8.352460e+17,2.625958e+07,2017-02-24 21:54:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@jonnysun @Lin_Manuel ok jomny I know you're e...,NaN,NaN,NaN,NaN,960,0,None,None,None,None,None
342,832088576586297345,8.320875e+17,3.058208e+07,2017-02-16 04:45:50 +0000,"<a href=""http://twitter.com/download/iphone"" r...",@docmisterio account started on 11/15/15,NaN,NaN,NaN,NaN,11,15,None,None,None,None,None
433,820690176645140481,NaN,NaN,2017-01-15 17:52:40 +0000,"<a href=""http://twitter.com/download/iphone"" r...",The floofs have been released I repeat the flo...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/820690176...,84,70,None,None,None,None,None
516,810984652412424192,NaN,NaN,2016-12-19 23:06:23 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Meet Sam. She smiles 24/7 &amp; secretly aspir...,NaN,NaN,NaN,"https://www.gofundme.com/sams-smile,https://tw...",24,7,Sam,None,None,None,None
784,775096608509886464,NaN,NaN,2016-09-11 22:20:06 +0000,"<a href=""http://twitter.com/download/iphone"" r...","RT @dog_rates: After so many requests, this is...",7.403732e+17,4.196984e+09,2016-06-08 02:41:38 +0000,https://twitter.com/dog_rates/status/740373189...,9,11,None,None,None,None,None
902,758467244762497024,NaN,NaN,2016-07-28 01:00:57 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Why does this never happen at my front door......,NaN,NaN,NaN,https://twitter.com/dog_rates/status/758467244...,165,150,None,None,None,None,None
1068,740373189193256964,NaN,NaN,2016-06-08 02:41:38 +0000,"<a href=""http://twitter.com/download/iphone"" r...","After so many requests, this is Bretagne. She ...",NaN,NaN,NaN,https://twitter.com/dog_rates/status/740373189...,9,11,None,None,None,None,None
1120,731156023742988288,NaN,NaN,2016-05-13 16:15:54 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Say hello to this unbelievably well behaved sq...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/731156023...,204,170,this,None,None,None,None
1165,722974582966214656,NaN,NaN,2016-04-21 02:25:47 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Happy 4/20 from the squad! 13/10 for all https...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/722974582...,4,20,None,None,None,None,None
1202,716439118184652801,NaN,NaN,2016-04-03 01:36:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Bluebert. He just saw that both #Final...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/716439118...,50,50,Bluebert,None,None,None,None
1228,713900603437621249,NaN,NaN,2016-03-27 01:29:02 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Happy Saturday here's 9 puppers on a bench. 99...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/713900603...,99,90,None,None,None,None,None
1254,710658690886586372,NaN,NaN,2016-03-18 02:46:49 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here's a brigade of puppers. All look very pre...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/710658690...,80,80,None,None,None,None,None
1274,709198395643068416,NaN,NaN,2016-03-14 02:04:08 +0000,"<a href=""http://twitter.com/download/iphone"" r...","From left to right:\nCletus, Jerome, Alejandro...",NaN,NaN,NaN,https://twitter.com/dog_rates/status/709198395...,45,50,None,None,None,None,None
1351,704054845121142784,NaN,NaN,2016-02-28 21:25:30 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here is a whole flock of puppers. 60/50 I'll ...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/704054845...,60,50,a,None,None,None,None
1433,697463031882764288,NaN,NaN,2016-02-10 16:51:59 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Happy Wednesday here's a bucket of pups. 44/40...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/697463031...,44,40,None,None,None,None,None
1598,686035780142297088,6.860340e+17,4.196984e+09,2016-01-10 04:04:10 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Yes I do realize a rating of 4/20 would've bee...,NaN,NaN,NaN,NaN,4,20,None,None,None,None,None
1634,684225744407494656,6.842229e+17,4.196984e+09,2016-01-05 04:11:44 +0000,"<a href=""http://twitter.com/download/iphone"" r...","Two sneaky puppers were not initially seen, mo...",NaN,NaN,NaN,https://twitter.com/dog_rates/status/684225744...,143,130,None,None,None,None,None
1635,684222868335505415,NaN,NaN,2016-01-05 04:00:18 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Someone help the girl is being mugged. Several...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/684222868...,121,110,None,None,None,None,None
1662,682962037429899265,NaN,NaN,2016-01-01 16:30:13 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is Darrel. He just robbed a 7/11 and is i...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/682962037...,7,11,Darrel,None,None,None,None
1663,682808988178739200,6.827884e+17,4.196984e+09,2016-01-01 06:22:03 +0000,"<a href=""http://twitter.com/download/iphone"" r...","I'm aware that I could've said 20/16, but here...",NaN,NaN,NaN,NaN,20,16,None,None,None,None,None
1779,677716515794329600,NaN,NaN,2015-12-18 05:06:23 +0000,"<a href=""http://twitter.com/download/iphone"" r...",IT'S PUPPERGEDDON. Total of 144/120 ...I think...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/677716515...,144,120,None,None,None,None,None
1843,675853064436391936,NaN,NaN,2015-12-13 01:41:41 +0000,"<a href=""http://twitter.com/download/iphone"" r...",Here we have an entire platoon of puppers. Tot...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/675853064...,88,80,None,None,None,None,None
2335,666287406224695296,NaN,NaN,2015-11-16 16:11:11 +0000,"<a href=""http://twitter.com/download/iphone"" r...",This is an Albanian 3 1/2 legged Episcopalian...,NaN,NaN,NaN,https://twitter.com/dog_rates/status/666287406...,1,2,an,None,None,None,None

In [214]:
twitter_df.rating_denominator.value_counts()

10     2333
11        3
50        3
80        2
20        2
2         1
16        1
40        1
70        1
15        1
90        1
110       1
120       1
130       1
150       1
170       1
7         1
0         1
Name: rating_denominator, dtype: int64

In [223]:
twitter_df.rating_numerator.describe()

count    2356.000000
mean       13.126486
std        45.876648
min         0.000000
25%        10.000000
50%        11.000000
75%        12.000000
max      1776.000000
Name: rating_numerator, dtype: float64

In [221]:
twitter_df.source.nunique() # it must be categorised

4

In [361]:
# API
API_df.head()

             tweet_id  retweet_count  favorite_count
0  892420643555336193           8549           38662
1  892177421306343426           6286           33126
2  891815181378084864           4166           24940
3  891689557279858688           8678           42033
4  891327558926688256           9435           40190

In [358]:
API_df.retweet_count.value_counts()

495      4
678      4
138      4
131      4
585      4
509      4
328      4
812      4
305      4
1263     4
1278     4
239      4
92       4
1171     4
719      4
390      4
252      4
1362     3
385      3
3610     3
242      3
65       3
913      3
849      3
97       3
2144     3
2159     3
1049     3
409      3
1058     3
        ..
477      1
2909     1
481      1
2532     1
8679     1
2536     1
451      1
439      1
2430     1
437      1
4479     1
387      1
2436     1
24967    1
399      1
2448     1
403      1
405      1
2458     1
411      1
2460     1
4513     1
419      1
425      1
427      1
429      1
431      1
2480     1
2484     1
0        1
Name: retweet_count, Length: 1745, dtype: int64

In [360]:
API_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2344 entries, 0 to 2343
Data columns (total 3 columns):
tweet_id          2344 non-null int64
retweet_count     2344 non-null int64
favorite_count    2344 non-null int64
dtypes: int64(3)
memory usage: 55.0 KB



# Clean
## <font color="green">Storing a copy</font>

In [776]:
twitter_clean = twitter_df.copy()
image_clean   = image_predictions_df.copy()
API_clean     = API_df.copy()

### Missing Data

#### `twitter_df` :  missing expanded_urls filling with it using        given tweet_id

##### Define
Copy the tweet_id to the missing expanded_urls

#### Code

In [777]:
tc=twitter_clean[twitter_clean.expanded_urls.isnull()].copy()
#https://twitter.com/dog_rates/status/885528943205470208/photo/1
tc['expanded_urls']=('https://twitter.com/dog_rates/status/'+tc['tweet_id'].astype(str)+'/photo/1').str.strip()
twitter_clean.update(tc,join='left',overwrite=False)

#### Test

In [778]:
(twitter_clean.expanded_urls.isnull()==True).sum()
#npw no null values in expanded_urls

0

In [779]:
twitter_clean.head()
twitter_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 17 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
timestamp                     2356 non-null object
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2356 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
dtypes: float64(4), int64(3), object(10)
memory usage: 313.0+ KB

### TIDENESS
#### timestamp column in `twitter_df` should be split into date and time column also convert the datatype of timestamp

#### Define

Extract the date and time from the timestamp column  using **str.split** method.Drop the contact coumn when done

#### Code

In [780]:
#we made 2 new columns
twitter_clean['date'] = twitter_Clean.timestamp.str.split(" ",1,expand=True)[0]
twitter_clean['time'] = twitter_Clean.timestamp.str.split(" ",1,expand=True)[1]

#drop timestamp column
twitter_clean.drop('timestamp',axis=1,inplace=True)

#### Test

In [781]:
twitter_clean.time
twitter_clean.date
twitter_clean.info()
list(twitter_clean) # lost all the updated columns of twiiter_clean

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 18 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2356 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
date                          2356 non-null object
time                          2356 non-null object
dtypes: float64(4), int64(3), object(11)
memory usage: 331.4+ KB

['tweet_id',
 'in_reply_to_status_id',
 'in_reply_to_user_id',
 'source',
 'text',
 'retweeted_status_id',
 'retweeted_status_user_id',
 'retweeted_status_timestamp',
 'expanded_urls',
 'rating_numerator',
 'rating_denominator',
 'name',
 'doggo',
 'floofer',
 'pupper',
 'puppo',
 'date',
 'time']

#### Four variables dog "stage" (i.e. doggo, floofer, pupper, and puppo) in 1 column knows as 'stages' in table `twitter_df`

#### Define

Melt the  doggo, floofer, pupper, and puppo columns to a new column **stage**

#### Code

In [782]:
# here we are making one more dataframe such that we can prove above definitions
twitter_clean2 = twitter_clean.copy()
list(twitter_clean2)

['tweet_id',
 'in_reply_to_status_id',
 'in_reply_to_user_id',
 'source',
 'text',
 'retweeted_status_id',
 'retweeted_status_user_id',
 'retweeted_status_timestamp',
 'expanded_urls',
 'rating_numerator',
 'rating_denominator',
 'name',
 'doggo',
 'floofer',
 'pupper',
 'puppo',
 'date',
 'time']

In [783]:
twitter_clean2 = pd.melt(twitter_clean2,
                       id_vars=['tweet_id','in_reply_to_status_id','in_reply_to_user_id','source','text','retweeted_status_id','retweeted_status_user_id','retweeted_status_timestamp','expanded_urls','rating_numerator','rating_denominator','name','date','time'],
                       var_name = 'stage',
                       value_name = 'value_at_stage')
twitter_clean2 = twitter_clean2[twitter_clean2.value_at_stage!='None']

#### Test

In [784]:
twitter_clean2.shape

(394, 16)

In [785]:
twitter_clean2.stage.nunique()

4

In [786]:
twitter_clean2.stage.value_counts()

pupper     257
doggo       97
puppo       30
floofer     10
Name: stage, dtype: int64

In [787]:
twitter_clean2.value_at_stage.value_counts()

pupper     257
doggo       97
puppo       30
floofer     10
Name: value_at_stage, dtype: int64

#### API_df should be part of `twitter_df`

#### Define

Merge the API_df table to the `twitter_df` table,joining on given **tweet_id**

#### Code

In [788]:
twitter_clean = pd.merge(twitter_clean,API_df,
                        on = ['tweet_id'],how='left')

In [789]:
twitter_clean.shape # no it has 20 columns, 2 more than previous.

(2356, 20)

In [790]:
twitter_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2356 entries, 0 to 2355
Data columns (total 20 columns):
tweet_id                      2356 non-null int64
in_reply_to_status_id         78 non-null float64
in_reply_to_user_id           78 non-null float64
source                        2356 non-null object
text                          2356 non-null object
retweeted_status_id           181 non-null float64
retweeted_status_user_id      181 non-null float64
retweeted_status_timestamp    181 non-null object
expanded_urls                 2356 non-null object
rating_numerator              2356 non-null int64
rating_denominator            2356 non-null int64
name                          2356 non-null object
doggo                         2356 non-null object
floofer                       2356 non-null object
pupper                        2356 non-null object
puppo                         2356 non-null object
date                          2356 non-null object
time                          2356 non-null object
retweet_count                 2344 non-null float64
favorite_count                2344 non-null float64
dtypes: float64(6), int64(3), object(11)
memory usage: 386.5+ KB

In [791]:
API_df.shape

(2344, 3)

In [803]:
# we should drop some rows, whose tweet's were not fetched frpm API

#list of rows to drop
twitter_clean[twitter_clean['retweet_count'].isnull()]
# drop those rows, for better table formation, these data is no longer required
twitter_clean.dropna(subset=['retweet_count','favorite_count'],inplace=True)  
twitter_clean[twitter_clean['retweet_count'].isnull()] # now no data is seen

Empty DataFrame
Columns: [tweet_id, in_reply_to_status_id, in_reply_to_user_id, source, text, retweeted_status_id, retweeted_status_user_id, retweeted_status_timestamp, expanded_urls, rating_numerator, rating_denominator, name, doggo, floofer, pupper, puppo, date, time, retweet_count, favorite_count]
Index: []


## Quality

#### wrong datatype for timestamp column(now date and time) and retweeted_status_timestamp

#### Define

convert the date and time column from string to datetime and same for retweeted_status_timestamp

#### Code

In [792]:
twitter_clean.date = pd.to_datetime(twitter_clean.date)
twitter_clean.time = pd.to_datetime(twitter_clean.time)
twitter_clean.retweeted_status_timestamp = pd.to_datetime(twitter_clean.retweeted_status_timestamp)

#### Test

In [813]:
twitter_clean.favorite_count.describe()

count      2344.000000
mean       8036.641212
std       12095.544435
min           0.000000
25%        1399.000000
50%        3524.500000
75%        9936.250000
max      142832.000000
Name: favorite_count, dtype: float64

#### wrong data type of retweeted and favorite count(also slice the .0 part

#### Define
Convert the retweeted and favorite  column's data type from a float to a string using astype, remove the '.0' using string slicing, and pad five and six digit zip codes with a leading 0.

#### Code

In [814]:
twitter_clean.retweet_count = twitter_clean.retweet_count.astype(str).str[:-2].str.pad(5,fillchar='0')
twitter_clean.favorite_count = twitter_clean.favorite_count.astype(str).str[:-2].str.pad(6,fillchar='0')

#### Code

In [816]:
twitter_clean.head()

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,date,time,retweet_count,favorite_count
0,892420643555336193,NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",This is Phineas. He's a mystical boy. Only eve...,NaN,NaN,NaT,https://twitter.com/dog_rates/status/892420643...,13,10,Phineas,None,None,None,None,2017-08-01,2018-07-10 16:23:56,08549,038662
1,892177421306343426,NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",This is Tilly. She's just checking pup on you....,NaN,NaN,NaT,https://twitter.com/dog_rates/status/892177421...,13,10,Tilly,None,None,None,None,2017-08-01,2018-07-10 00:17:27,06286,033126
2,891815181378084864,NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",This is Archie. He is a rare Norwegian Pouncin...,NaN,NaN,NaT,https://twitter.com/dog_rates/status/891815181...,12,10,Archie,None,None,None,None,2017-07-31,2018-07-10 00:18:03,04166,024940
3,891689557279858688,NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",This is Darla. She commenced a snooze mid meal...,NaN,NaN,NaT,https://twitter.com/dog_rates/status/891689557...,13,10,Darla,None,None,None,None,2017-07-30,2018-07-10 15:58:51,08678,042033
4,891327558926688256,NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",This is Franklin. He would like you to stop ca...,NaN,NaN,NaT,https://twitter.com/dog_rates/status/891327558...,12,10,Franklin,None,None,None,None,2017-07-29,2018-07-10 16:00:24,09435,040190

#### wrongly extraction of name {'a','an'} in name column, there must be none in place in `twitter_df` table.

### Define

Replace the a and an from name column with None as have others rows wherever, name is not cleared using `replace method`

### Code

In [818]:
twitter_clean.name = twitter_clean.name.replace('a','None')
twitter_clean.name = twitter_clean.name.replace('an','None')

### Test

In [824]:
#should be empty
twitter_clean[twitter_clean.name=='a']
twitter_clean[twitter_clean.name=='an']

Empty DataFrame
Columns: [tweet_id, in_reply_to_status_id, in_reply_to_user_id, source, text, retweeted_status_id, retweeted_status_user_id, retweeted_status_timestamp, expanded_urls, rating_numerator, rating_denominator, name, doggo, floofer, pupper, puppo, date, time, retweet_count, favorite_count]
Index: []

#### since we have only 4 types of sources so it must be categorised in `twitter_df` table

#### Define
Convert the sources to categorical data types using `astype` method

#### Code

In [827]:
twitter_clean.source = twitter_clean.source.astype('category')

#### Test

In [829]:
# now it is categorical types
twitter_clean.source.dtype

CategoricalDtype(categories=['<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
                  '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
                  '<a href="http://vine.co" rel="nofollow">Vine - Make a Scene</a>',
                  '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>'],
                 ordered=False)

#### for row 47(name is Bella) and 763(name is Sophie) wrong extraction is taken place 11.27 to 27 qnd 13.5 to 5 means wrong conversion is taken for decimal point numerator.

### Define
we need to replace/update the particular value

### Code

In [861]:
#twitter_clean.info()
# to row number 765
twitter_clean.loc[763,'rating_numerator']=11.27

#to row number 47
twitter_clean.loc[47,'rating_numerator']=13.5

### Test

In [862]:
#returns 1 row
twitter_clean.query('rating_numerator==11.27')
#twitter_clean.query('rating_numerator==13.5')

,tweet_id,in_reply_to_status_id,in_reply_to_user_id,source,text,retweeted_status_id,retweeted_status_user_id,retweeted_status_timestamp,expanded_urls,rating_numerator,rating_denominator,name,doggo,floofer,pupper,puppo,date,time,retweet_count,favorite_count
763,778027034220126208,NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",This is Sophie. She's a Jubilant Bush Pupper. ...,NaN,NaN,NaT,https://twitter.com/dog_rates/status/778027034...,11.27,10,Sophie,None,None,pupper,None,2016-09-20,2018-07-10 00:24:34,01813,007126
765,777885040357281792,NaN,NaN,"<a href=""http://twitter.com/download/iphone"" r...",This is Wesley. He's clearly trespassing. Seem...,NaN,NaN,NaT,https://twitter.com/dog_rates/status/777885040...,11.27,10,Wesley,None,None,None,None,2016-09-19,2018-07-10 15:00:20,01834,006898